# Generated by Django 5.2.3 on 2025-07-02 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_stocks_remove_userstock_stock_remove_userinfo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panCard', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='profile_pic/')),
                ('panCard_Image', models.ImageField(upload_to='', verbose_name='pancard/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
