# Generated by Django 5.2.3 on 2025-07-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_userstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='id',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
