# Generated by Django 5.2.3 on 2025-07-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_stocks_id_alter_stocks_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
